version: '2'

services:
  video-streaming:
    build: ./streaming
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
  video-capture:
    build: ./rtsp-server
    network_mode: host
    privileged: true
