FROM balenalib/%%BALENA_MACHINE_NAME%%

RUN apt-get update && \
    apt-get install -y vim git nano gstreamer1.0-tools \
    libgstrtspserver-1.0-dev gstreamer1.0-rtsp

WORKDIR /usr/src/app


CMD ["sleep", "infinity"]
