version: '2'

services:
  video-streaming:
    build: .
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
  video-capture:
    image: alanb128/video-capture:pi-20210717
    network_mode: host
    privileged: true
    labels:
          io.balena.features.balena-api: '1'
